export {default as Home} from './Home/Home'
export {default as Register} from './Register/Register'
export {default as Login} from './Login/Login'
export {default as Plan} from './Plan/Plan'
export {default as About} from './About/About'
export {default as Profile} from './Profile/Profile'