export const FETCH_USER = 'FETCH_USER'
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const FETCH_PLANS = 'FETCH_PLANS'
export const ADD_PLAN = 'ADD_PLAN'
export const ADD_ACTIVITY = 'ADD_ACTIVITY'